export { default as Hamburger } from "./hamburger.svg";
export { default as Home } from "./home.svg";
export { default as Category } from "./category.svg";
export { default as Upload } from "./upload.svg";
export { default as Delete } from "./delete.svg";
export { default as Plus } from "./plus.svg";
export { default as DeleteRed } from "./deleteRed.svg";
export { default as Options } from "./option.svg";
export { default as EditPencil } from "./editPencil.svg";
